CREATE TABLE [dbo].[CONFIG] (
    [PK_ID_CONFIG] INT            IDENTITY (1, 1) NOT NULL,
    [CONFIG_NAME]  NVARCHAR (MAX) NULL,
    [CONFIG_VALUE] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CONFIG] PRIMARY KEY CLUSTERED ([PK_ID_CONFIG] ASC)
);

