CREATE TABLE [dbo].[FORMAT] (
    [PK_ID_FORMAT]        INT            IDENTITY (1, 1) NOT NULL,
    [FORMAT_NAME]         NVARCHAR (50)  NULL,
    [FORMAT_FFMPEG_VALUE] NVARCHAR (MAX) NULL,
    [IS_ENABLED]          BIT            NOT NULL,
    [FK_ID_FORMAT_TYPE]   INT            NULL,
    [FK_ID_FORMAT_BASE]   INT            NULL,
    CONSTRAINT [PK_FORMAT] PRIMARY KEY CLUSTERED ([PK_ID_FORMAT] ASC),
    CONSTRAINT [FK_FORMAT_FORMAT_TYPE] FOREIGN KEY ([FK_ID_FORMAT_TYPE]) REFERENCES [dbo].[FORMAT_TYPE] ([PK_ID_FORMAT_TYPE])
);





