CREATE TABLE [dbo].[FORMAT] (
    [PK_ID_FORMAT]        INT            IDENTITY (1, 1) NOT NULL,
    [FORMAT_NAME]         NVARCHAR (50)  NULL,
    [FORMAT_FFMPEG_VALUE] NVARCHAR (MAX) NULL,
    [IS_ENABLED]          BIT            NOT NULL,
    [FK_ID_FORMAT_TYPE]   INT            NULL,
    CONSTRAINT [PK_FORMAT] PRIMARY KEY CLUSTERED ([PK_ID_FORMAT] ASC)
);

