CREATE TABLE [dbo].[FORMAT_TYPE] (
    [PK_ID_FORMAT_TYPE] INT            IDENTITY (1, 1) NOT NULL,
    [FORMAT_TYPE_NAME]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_FORMAT_TYPE] PRIMARY KEY CLUSTERED ([PK_ID_FORMAT_TYPE] ASC)
);

