CREATE TABLE [dbo].[PARAM_SPLIT] (
    [PK_ID_PARAM_SPLIT] INT            IDENTITY (1, 1) NOT NULL,
    [BEGIN_PARAM_SPLIT] NVARCHAR (MAX) NULL,
    [END_PARAM_SPLIT]   NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_PARAM_SPLIT] PRIMARY KEY CLUSTERED ([PK_ID_PARAM_SPLIT] ASC)
);



