CREATE TABLE [dbo].[PARAM_LENGTH] (
    [PK_ID_PARAM_LENGTH] INT        IDENTITY (1, 1) NOT NULL,
    [LENGTH]             FLOAT (53) NULL,
    [NB_OF_SPLITS]       INT        NULL,
    CONSTRAINT [PK_PARAM_LENGTH] PRIMARY KEY CLUSTERED ([PK_ID_PARAM_LENGTH] ASC)
);

