CREATE TABLE [dbo].[PARAM_TASK_STATUS] (
    [PK_ID_STATUS] INT           IDENTITY (1, 1) NOT NULL,
    [LIBELLE]      NVARCHAR (50) NOT NULL,
    [IS_ACTIVE]    BIT           NOT NULL,
    CONSTRAINT [PK_PARAM_TASK_STATUS] PRIMARY KEY CLUSTERED ([PK_ID_STATUS] ASC)
);

