CREATE TABLE [dbo].[TRACE] (
    [PK_ID_TRACE]  INT            IDENTITY (1, 1) NOT NULL,
    [FK_ID_TASK]   INT            NOT NULL,
    [FK_ID_SERVER] INT            NOT NULL,
    [METHOD]       NVARCHAR (MAX) NULL,
    [DESCRIPTION]  NVARCHAR (MAX) NULL,
    [TYPE]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_TRACE] PRIMARY KEY CLUSTERED ([PK_ID_TRACE] ASC)
);

