CREATE TABLE [dbo].[TRANSACTION] (
    [PK_ID_TRANSACTION]     INT        IDENTITY (1, 1) NOT NULL,
    [FK_ID_USER]            INT        NOT NULL,
    [PRICE]                 FLOAT (53) NOT NULL,
    [DATE_TRANSACTION]      DATETIME   NOT NULL,
    [PAYPAL_TRANSACTION_ID] BIGINT     NULL,
    CONSTRAINT [PK_TRANSACTION] PRIMARY KEY CLUSTERED ([PK_ID_TRANSACTION] ASC),
    CONSTRAINT [FK_TRANSACTION_USER] FOREIGN KEY ([FK_ID_USER]) REFERENCES [dbo].[USER] ([PK_ID_USER])
);



