CREATE TABLE [dbo].[TRANSACTION] (
    [PK_ID_TRANSACTION]   INT        IDENTITY (1, 1) NOT NULL,
    [FK_ID_USER]          INT        NOT NULL,
    [FK_ID_TASK]          INT        NOT NULL,
    [PRICE]               FLOAT (53) NOT NULL,
    [DATE_TRANSACTION]    DATETIME   NOT NULL,
    [FK_ID_MODE_PAIEMENT] INT        NOT NULL,
    CONSTRAINT [PK_TRANSACTION] PRIMARY KEY CLUSTERED ([PK_ID_TRANSACTION] ASC),
    CONSTRAINT [FK_TRANSACTION_MODE_PAIEMENT] FOREIGN KEY ([FK_ID_MODE_PAIEMENT]) REFERENCES [dbo].[MODE_PAIEMENT] ([PK_ID_MODE_PAIEMENT]),
    CONSTRAINT [FK_TRANSACTION_TASK] FOREIGN KEY ([FK_ID_TASK]) REFERENCES [dbo].[TASK] ([PK_ID_TASK]),
    CONSTRAINT [FK_TRANSACTION_USER] FOREIGN KEY ([FK_ID_USER]) REFERENCES [dbo].[USER] ([PK_ID_USER])
);

