CREATE TABLE [dbo].[USER] (
    [PK_ID_USER] INT           IDENTITY (1, 1) NOT NULL,
    [USERNAME]   NVARCHAR (50) NULL,
    [PASSWORD]   NVARCHAR (50) NULL,
    [FIRSTNAME]  NVARCHAR (50) NULL,
    [LASTNAME]   NVARCHAR (50) NULL,
    [BIRTHDATE]  NVARCHAR (50) NULL,
    [EMAIL]      NVARCHAR (50) NULL,
    [FACEBOOKID] NVARCHAR (50) NULL,
    [GOOGLEID]   NVARCHAR (50) NULL,
    CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED ([PK_ID_USER] ASC)
);

