//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Transcoder.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG
    {
        public int PK_ID_CONFIG { get; set; }
        public string CONFIG_NAME { get; set; }
        public string CONFIG_VALUE { get; set; }
    }
}
