//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Transcoder.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMAT()
        {
            this.TASK = new HashSet<TASK>();
        }
    
        public int PK_ID_FORMAT { get; set; }
        public string FORMAT_NAME { get; set; }
        public string FORMAT_FFMPEG_VALUE { get; set; }
        public bool IS_ENABLED { get; set; }
        public Nullable<int> FK_ID_FORMAT_TYPE { get; set; }
    
        public virtual FORMAT_TYPE FORMAT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASK { get; set; }
    }
}
