//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Transcoder.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM_SPLIT
    {
        public int PK_ID_PARAM_SPLIT { get; set; }
        public string BEGIN_PARAM_SPLIT { get; set; }
        public string END_PARAM_SPLIT { get; set; }
    }
}
