//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Transcoder.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int PK_ID_TRANSACTION { get; set; }
        public int FK_ID_USER { get; set; }
        public int FK_ID_TASK { get; set; }
        public double PRICE { get; set; }
        public System.DateTime DATE_TRANSACTION { get; set; }
        public int FK_ID_MODE_PAIEMENT { get; set; }
    
        public virtual MODE_PAIEMENT MODE_PAIEMENT { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual USER USER { get; set; }
    }
}
