//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Transcoder.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Transcoder.Utils.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir le format de conversion.
        /// </summary>
        public static string add_conversion_choose_destination_format {
            get {
                return ResourceManager.GetString("add_conversion_choose_destination_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Url du fichier.
        /// </summary>
        public static string add_conversion_file_url {
            get {
                return ResourceManager.GetString("add_conversion_file_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charger le fichier.
        /// </summary>
        public static string add_conversion_load_file {
            get {
                return ResourceManager.GetString("add_conversion_load_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Fichier local.
        /// </summary>
        public static string add_conversion_local_file {
            get {
                return ResourceManager.GetString("add_conversion_local_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre demande de conversion a été ajouté au panier..
        /// </summary>
        public static string add_conversion_message_added_to_cart {
            get {
                return ResourceManager.GetString("add_conversion_message_added_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre panier a été validé, vous allez recevoir un mail de confirmation..
        /// </summary>
        public static string add_conversion_message_cart_validated {
            get {
                return ResourceManager.GetString("add_conversion_message_cart_validated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter la conversion.
        /// </summary>
        public static string addconversion_button_add_conversion {
            get {
                return ResourceManager.GetString("addconversion_button_add_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commander Maintenant !.
        /// </summary>
        public static string addconversion_button_order_now {
            get {
                return ResourceManager.GetString("addconversion_button_order_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouté au panier.
        /// </summary>
        public static string addconversion_cart_added {
            get {
                return ResourceManager.GetString("addconversion_cart_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir votre fichier.
        /// </summary>
        public static string addconversion_choice_file {
            get {
                return ResourceManager.GetString("addconversion_choice_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;envoi.
        /// </summary>
        public static string addconversion_error_sending {
            get {
                return ResourceManager.GetString("addconversion_error_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;élément téléchargé ne peut pas être converti, veuillez en choisir un autre..
        /// </summary>
        public static string addconversion_error_source_file {
            get {
                return ResourceManager.GetString("addconversion_error_source_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de destination.
        /// </summary>
        public static string addconversion_form_convertedformat {
            get {
                return ResourceManager.GetString("addconversion_form_convertedformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du fichier.
        /// </summary>
        public static string addconversion_form_filename {
            get {
                return ResourceManager.GetString("addconversion_form_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée(minutes).
        /// </summary>
        public static string addconversion_form_length {
            get {
                return ResourceManager.GetString("addconversion_form_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format d&apos;origine.
        /// </summary>
        public static string addconversion_form_originformat {
            get {
                return ResourceManager.GetString("addconversion_form_originformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        public static string addconversion_form_price {
            get {
                return ResourceManager.GetString("addconversion_form_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut.
        /// </summary>
        public static string addconversion_form_status {
            get {
                return ResourceManager.GetString("addconversion_form_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format de conversion :.
        /// </summary>
        public static string addconversion_format_conversion {
            get {
                return ResourceManager.GetString("addconversion_format_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider votre commande.
        /// </summary>
        public static string addconversion_page_title_valid_command {
            get {
                return ResourceManager.GetString("addconversion_page_title_valid_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un type de conversion :.
        /// </summary>
        public static string addconversion_select_conversion_type {
            get {
                return ResourceManager.GetString("addconversion_select_conversion_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner un fichier.
        /// </summary>
        public static string addconversion_select_file {
            get {
                return ResourceManager.GetString("addconversion_select_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectioner un format :.
        /// </summary>
        public static string addconversion_select_format {
            get {
                return ResourceManager.GetString("addconversion_select_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une conversion.
        /// </summary>
        public static string addconversion_title {
            get {
                return ResourceManager.GetString("addconversion_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de conversion : .
        /// </summary>
        public static string addconversion_type_conversion {
            get {
                return ResourceManager.GetString("addconversion_type_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transcoder.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convertir vos médias n&apos;a jamais été aussi facile.
        /// </summary>
        public static string app_summary {
            get {
                return ResourceManager.GetString("app_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant total de votre commande : .
        /// </summary>
        public static string cart_order_amount {
            get {
                return ResourceManager.GetString("cart_order_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon panier.
        /// </summary>
        public static string cart_page_title {
            get {
                return ResourceManager.GetString("cart_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string conversion_button_delete {
            get {
                return ResourceManager.GetString("conversion_button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Télécharger.
        /// </summary>
        public static string conversion_button_download {
            get {
                return ResourceManager.GetString("conversion_button_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier votre compte.
        /// </summary>
        public static string editprofile_page_title {
            get {
                return ResourceManager.GetString("editprofile_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profitez pleinement des fonctionnalités ! .
        /// </summary>
        public static string home_auth_subtitle {
            get {
                return ResourceManager.GetString("home_auth_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur Transcoder.
        /// </summary>
        public static string home_auth_title {
            get {
                return ResourceManager.GetString("home_auth_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ma derniere demande de conversion  :.
        /// </summary>
        public static string home_auth_title_task {
            get {
                return ResourceManager.GetString("home_auth_title_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Essayez dès maintenant !.
        /// </summary>
        public static string home_button_get_started {
            get {
                return ResourceManager.GetString("home_button_get_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conversions.
        /// </summary>
        public static string home_gauge_conversions_datalabel {
            get {
                return ResourceManager.GetString("home_gauge_conversions_datalabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formats.
        /// </summary>
        public static string home_gauge_formats_datalabel {
            get {
                return ResourceManager.GetString("home_gauge_formats_datalabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs.
        /// </summary>
        public static string home_gauge_users_datalabel {
            get {
                return ResourceManager.GetString("home_gauge_users_datalabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contribuez aux nouveautés et améliorations de Transcoder.
        /// </summary>
        public static string home_guest_community_text {
            get {
                return ResourceManager.GetString("home_guest_community_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communauté.
        /// </summary>
        public static string home_guest_community_title {
            get {
                return ResourceManager.GetString("home_guest_community_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connectez-vous grâce à vos comptes Google ou Facebook, et accédez depuis n&apos;importe quel périphérique à vos conversions..
        /// </summary>
        public static string home_guest_social_text {
            get {
                return ResourceManager.GetString("home_guest_social_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restez connecté.
        /// </summary>
        public static string home_guest_social_title {
            get {
                return ResourceManager.GetString("home_guest_social_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle conversion.
        /// </summary>
        public static string listconversion_button_add_conversion {
            get {
                return ResourceManager.GetString("listconversion_button_add_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes conversions.
        /// </summary>
        public static string listconversion_page_title {
            get {
                return ResourceManager.GetString("listconversion_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string login_button_valid {
            get {
                return ResourceManager.GetString("login_button_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;authentification.
        /// </summary>
        public static string login_error_auth {
            get {
                return ResourceManager.GetString("login_error_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tentative de connexion non valide.
        /// </summary>
        public static string login_error_invalid_connexion {
            get {
                return ResourceManager.GetString("login_error_invalid_connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string login_form_password {
            get {
                return ResourceManager.GetString("login_form_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string login_form_username {
            get {
                return ResourceManager.GetString("login_form_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez été déconnecté.
        /// </summary>
        public static string login_message_disconnected {
            get {
                return ResourceManager.GetString("login_message_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string login_page_title {
            get {
                return ResourceManager.GetString("login_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mémoriser le mot de passe ?.
        /// </summary>
        public static string login_remember_me {
            get {
                return ResourceManager.GetString("login_remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connectez-vous avec.
        /// </summary>
        public static string login_section_social_title {
            get {
                return ResourceManager.GetString("login_section_social_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ou utilisez un compte standard.
        /// </summary>
        public static string login_section_title_standard_account {
            get {
                return ResourceManager.GetString("login_section_title_standard_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panier.
        /// </summary>
        public static string navbar_button_cart {
            get {
                return ResourceManager.GetString("navbar_button_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conversion.
        /// </summary>
        public static string navbar_button_conversion {
            get {
                return ResourceManager.GetString("navbar_button_conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier mon profil.
        /// </summary>
        public static string navbar_button_edit_profile {
            get {
                return ResourceManager.GetString("navbar_button_edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string navbar_button_login {
            get {
                return ResourceManager.GetString("navbar_button_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string navbar_button_logout {
            get {
                return ResourceManager.GetString("navbar_button_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes conversions.
        /// </summary>
        public static string navbar_button_myconversions {
            get {
                return ResourceManager.GetString("navbar_button_myconversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string navbar_button_register {
            get {
                return ResourceManager.GetString("navbar_button_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour {0} !.
        /// </summary>
        public static string navbar_hello_user {
            get {
                return ResourceManager.GetString("navbar_hello_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string register_button_valid {
            get {
                return ResourceManager.GetString("register_button_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le pseudo ou l&apos;email existe déjà, veuillez en choisir un autre..
        /// </summary>
        public static string register_error_user_already_exists {
            get {
                return ResourceManager.GetString("register_error_user_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string register_form_email {
            get {
                return ResourceManager.GetString("register_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string register_form_password {
            get {
                return ResourceManager.GetString("register_form_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer le mot de passe.
        /// </summary>
        public static string register_form_password_confirm {
            get {
                return ResourceManager.GetString("register_form_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string register_form_username {
            get {
                return ResourceManager.GetString("register_form_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string register_page_title {
            get {
                return ResourceManager.GetString("register_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ou crée un compte standard.
        /// </summary>
        public static string register_section_title_standard_account {
            get {
                return ResourceManager.GetString("register_section_title_standard_account", resourceCulture);
            }
        }
    }
}
